INFO 2025-01-23 16:28:00,189 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 16:47:49,697 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 16:48:06,064 basehttp "GET /test HTTP/1.1" 200 38
INFO 2025-01-23 16:49:40,589 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-23 16:49:41,862 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 16:49:42,783 basehttp "GET /test HTTP/1.1" 200 186
INFO 2025-01-23 16:55:42,094 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\DjangoBlog\settings.py changed, reloading.
INFO 2025-01-23 16:55:43,170 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 16:58:09,053 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-23 16:58:10,033 autoreload Watching for file changes with StatReloader
WARNING 2025-01-23 16:58:17,462 log Not Found: /article/test
WARNING 2025-01-23 16:58:17,463 basehttp "GET /article/test HTTP/1.1" 404 3061
INFO 2025-01-23 17:01:04,145 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\DjangoBlog\urls.py changed, reloading.
INFO 2025-01-23 17:01:05,186 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 17:01:10,338 basehttp "GET /article/test HTTP/1.1" 200 317
INFO 2025-01-23 17:01:10,407 basehttp "GET /static/bootstrap5/js/bootstrap.js HTTP/1.1" 200 145819
INFO 2025-01-23 17:01:10,409 basehttp "GET /static/bootstrap5/css/bootstrap.css HTTP/1.1" 200 267476
INFO 2025-01-23 17:11:21,483 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\urls.py changed, reloading.
INFO 2025-01-23 17:11:22,496 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 17:11:37,394 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\urls.py changed, reloading.
INFO 2025-01-23 17:11:38,354 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 17:12:31,958 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\DjangoBlog\urls.py changed, reloading.
INFO 2025-01-23 17:12:32,994 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 17:12:34,120 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-01-23 17:12:34,131 basehttp "GET /user/login.html HTTP/1.1" 200 4316
INFO 2025-01-23 17:12:34,248 basehttp "GET /static/css/login.css HTTP/1.1" 200 2979
INFO 2025-01-23 17:12:34,249 basehttp "GET /static/js/jquery-1.11.2.min.js HTTP/1.1" 200 95931
INFO 2025-01-23 17:12:34,272 basehttp "GET /static/images/hand.png HTTP/1.1" 200 1061
INFO 2025-01-23 17:12:34,272 basehttp "GET /static/images/tou.png HTTP/1.1" 200 9217
INFO 2025-01-23 17:12:34,273 basehttp "GET /static/images/username.png HTTP/1.1" 200 546
INFO 2025-01-23 17:12:34,273 basehttp "GET /static/images/password.png HTTP/1.1" 200 510
INFO 2025-01-23 17:13:04,571 basehttp "GET / HTTP/1.1" 302 0
INFO 2025-01-23 17:13:04,578 basehttp "GET /user/login.html HTTP/1.1" 200 4316
INFO 2025-01-23 17:13:04,597 basehttp "GET /static/css/login.css HTTP/1.1" 200 2979
INFO 2025-01-23 17:13:04,598 basehttp "GET /static/js/jquery-1.11.2.min.js HTTP/1.1" 200 95931
INFO 2025-01-23 17:13:04,613 basehttp "GET /static/images/hand.png HTTP/1.1" 200 1061
INFO 2025-01-23 17:13:04,614 basehttp "GET /static/images/tou.png HTTP/1.1" 200 9217
INFO 2025-01-23 17:13:04,619 basehttp "GET /static/images/username.png HTTP/1.1" 200 546
INFO 2025-01-23 17:13:04,619 basehttp "GET /static/images/password.png HTTP/1.1" 200 510
INFO 2025-01-23 17:15:27,190 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-23 17:15:29,617 basehttp "GET /user/login.html HTTP/1.1" 200 4316
INFO 2025-01-23 17:20:03,013 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\models.py changed, reloading.
INFO 2025-01-23 17:20:04,049 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 17:20:16,992 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\models.py changed, reloading.
INFO 2025-01-23 17:20:17,909 autoreload Watching for file changes with StatReloader
INFO 2025-01-23 17:21:19,961 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\DjangoBlog\settings.py changed, reloading.
INFO 2025-01-23 17:21:20,891 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 09:53:40,993 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 09:53:56,879 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 09:54:07,412 basehttp "GET /static/images/left_hand.png HTTP/1.1" 200 1469
INFO 2025-01-24 09:54:07,415 basehttp "GET /static/images/right_hand.png HTTP/1.1" 200 1370
INFO 2025-01-24 09:54:25,312 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 09:54:26,504 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 09:55:39,769 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 09:55:40,796 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 09:58:30,596 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 09:58:31,678 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 09:59:16,845 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 09:59:17,825 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:00:58,756 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 10:00:59,725 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:06:33,826 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-24 10:06:34,894 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:07:29,137 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-24 10:07:30,210 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:07:47,794 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-24 10:07:48,882 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:11:17,147 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-24 10:11:18,108 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:14:03,548 autoreload Watching for file changes with StatReloader
WARNING 2025-01-24 10:14:16,750 log Not Found: /
WARNING 2025-01-24 10:14:16,750 basehttp "GET / HTTP/1.1" 404 2908
WARNING 2025-01-24 10:14:16,805 log Not Found: /favicon.ico
WARNING 2025-01-24 10:14:16,806 basehttp "GET /favicon.ico HTTP/1.1" 404 2959
INFO 2025-01-24 10:14:28,356 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 10:14:30,292 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 10:14:30,978 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 10:14:31,395 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 10:14:31,638 basehttp "GET /user/register.html HTTP/1.1" 200 6229
INFO 2025-01-24 10:14:55,052 basehttp "POST /user/register HTTP/1.1" 200 6244
INFO 2025-01-24 10:17:46,258 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:18:04,781 basehttp "GET /user/register.html HTTP/1.1" 200 6287
ERROR 2025-01-24 10:18:18,872 log Internal Server Error: /user/register
Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'analytics' for key 'user_myuser.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py", line 44, in register
    user = MyUser.objects.create_user(**d)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\contrib\auth\models.py", line 162, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\contrib\auth\models.py", line 156, in _create_user
    user.save(using=self._db)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'analytics' for key 'user_myuser.username'")
INFO 2025-01-24 10:18:18,888 basehttp - Broken pipe from ('127.0.0.1', 64984)
ERROR 2025-01-24 10:18:19,654 log Internal Server Error: /user/register
Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1062, "Duplicate entry 'analytics' for key 'user_myuser.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py", line 44, in register
    user = MyUser.objects.create_user(**d)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\contrib\auth\models.py", line 162, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\contrib\auth\models.py", line 156, in _create_user
    user.save(using=self._db)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'analytics' for key 'user_myuser.username'")
ERROR 2025-01-24 10:18:19,664 basehttp "POST /user/register HTTP/1.1" 500 223008
INFO 2025-01-24 10:19:05,410 basehttp "POST /user/register HTTP/1.1" 200 6301
INFO 2025-01-24 10:19:11,140 basehttp "GET /user/login.html HTTP/1.1" 200 4394
WARNING 2025-01-24 10:19:17,371 log Not Found: /user/login
WARNING 2025-01-24 10:19:17,371 basehttp "POST /user/login HTTP/1.1" 404 3618
INFO 2025-01-24 10:21:54,067 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 10:21:55,182 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:23:10,076 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 10:23:11,139 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:23:37,126 basehttp "POST /user/login HTTP/1.1" 200 4409
INFO 2025-01-24 10:23:39,482 basehttp "POST /user/login HTTP/1.1" 200 4409
INFO 2025-01-24 10:23:41,917 basehttp "POST /user/login HTTP/1.1" 200 4409
INFO 2025-01-24 10:23:43,022 basehttp "POST /user/login HTTP/1.1" 200 4409
INFO 2025-01-24 10:23:49,126 basehttp "POST /user/login HTTP/1.1" 200 4409
INFO 2025-01-24 10:23:53,975 basehttp "GET /user/register.html HTTP/1.1" 200 6287
INFO 2025-01-24 10:23:55,523 basehttp "GET /user/register.html HTTP/1.1" 200 6287
INFO 2025-01-24 10:23:56,972 basehttp "GET /user/login.html HTTP/1.1" 200 4394
INFO 2025-01-24 10:24:41,647 basehttp "POST /user/login HTTP/1.1" 200 4409
INFO 2025-01-24 10:25:11,851 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\user\views.py changed, reloading.
INFO 2025-01-24 10:25:12,839 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:25:18,079 basehttp "POST /user/login HTTP/1.1" 302 0
ERROR 2025-01-24 10:25:18,168 log Internal Server Error: /article/2/1/0.html
Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py", line 32, in article
    return render(request, 'article.html', locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\backends\django.py", line 103, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\context.py", line 288, in make_context
    raise TypeError(
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2025-01-24 10:25:18,171 basehttp "GET /article/2/1/0.html HTTP/1.1" 500 100443
ERROR 2025-01-24 10:29:44,677 log Internal Server Error: /article/2/1/0.html
Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py", line 32, in article
    return render(request, 'article.html', locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\backends\django.py", line 103, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\context.py", line 288, in make_context
    raise TypeError(
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2025-01-24 10:29:44,679 basehttp "GET /article/2/1/0.html HTTP/1.1" 500 100443
INFO 2025-01-24 10:29:53,688 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\urls.py changed, reloading.
INFO 2025-01-24 10:29:54,701 autoreload Watching for file changes with StatReloader
WARNING 2025-01-24 10:29:55,489 log Not Found: /article/2/1/0.html
WARNING 2025-01-24 10:29:55,491 basehttp "GET /article/2/1/0.html HTTP/1.1" 404 3635
ERROR 2025-01-24 10:30:09,151 log Internal Server Error: /article/2/1/0
Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py", line 32, in article
    return render(request, 'article.html', locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\backends\django.py", line 103, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\context.py", line 288, in make_context
    raise TypeError(
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2025-01-24 10:30:09,158 basehttp "GET /article/2/1/0 HTTP/1.1" 500 100075
INFO 2025-01-24 10:30:36,721 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\urls.py changed, reloading.
INFO 2025-01-24 10:30:37,701 autoreload Watching for file changes with StatReloader
INFO 2025-01-24 10:32:38,856 basehttp "GET /user/login.html HTTP/1.1" 200 4394
INFO 2025-01-24 10:32:44,045 basehttp "POST /user/login HTTP/1.1" 302 0
ERROR 2025-01-24 10:32:46,714 log Internal Server Error: /article/2/1/0.html
Traceback (most recent call last):
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py", line 32, in article
    return render(request, 'article.html', locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\backends\django.py", line 103, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "D:\Workspace\PycharmProjects\python-project\DjangoBlog\.venv\Lib\site-packages\django\template\context.py", line 288, in make_context
    raise TypeError(
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2025-01-24 10:32:46,714 basehttp "GET /article/2/1/0.html HTTP/1.1" 500 100448
INFO 2025-01-24 10:34:19,415 autoreload D:\Workspace\PycharmProjects\python-project\DjangoBlog\article\views.py changed, reloading.
INFO 2025-01-24 10:34:20,371 autoreload Watching for file changes with StatReloader
